# Generated by Django 5.2.8 on 2025-11-30 17:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_update_fish_model_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='date_purchased',
            field=models.DateField(help_text='Date when fish was purchased to track freshness'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Total price for this fish', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='fish',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, help_text='Weight of fish in kilograms', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.DeleteModel(
            name='SellerProfile',
        ),
    ]
