# Generated by Django for adding new fields to Fish model

from django.db import migrations, models
import django.core.validators
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_update_fish_model_fields'),
    ]

    operations = [
        # Add new required fields
        migrations.AddField(
            model_name='fish',
            name='weight_kg',
            field=models.DecimalField(
                decimal_places=2, 
                max_digits=10, 
                validators=[django.core.validators.MinValueValidator(Decimal('0.01'))],
                help_text="Weight of fish in kilograms",
                null=True,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='fish',
            name='total_price',
            field=models.DecimalField(
                decimal_places=2, 
                max_digits=10, 
                validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
                help_text="Total price for this fish",
                null=True,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='fish',
            name='date_purchased',
            field=models.DateField(
                help_text="Date when fish was purchased to track freshness",
                null=True,
                blank=True
            ),
        ),
    ]
